/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WePLi.UserFrame;

import WePLi.UI.JFrameSetting;
import WePLi.UI.JPanelSetting;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Donghyeon <20183188>
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    private ArrayList<JPanel> panelList = new ArrayList<>();

    public LoginJFrame() {
        JFrameSetting.layoutInit();
        
        setResizable(false); // 크기 변경 불가능하도록 함
        setUndecorated(true); // 프레임의 타이틀바를 없앰
        
        initComponents();

        setVisible(true);
        // 화면 중앙에서 실행
        setLocationRelativeTo(null);
        
        this.panelList.add(this.loginPanel);
        this.panelList.add(this.signUpPanel);

        JPanelSetting.changePanel(panelList, loginPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpPanel = new javax.swing.JPanel();
        loginTextLabel = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        checkPwField = new javax.swing.JPasswordField();
        checkPwLabel = new javax.swing.JLabel();
        signUpIdTextField = new javax.swing.JTextField();
        signUpIdLabel = new javax.swing.JLabel();
        signUpPwTextField = new javax.swing.JPasswordField();
        signUpPwLabel = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        SignUpTextLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        pwTextField = new javax.swing.JPasswordField();
        IdFieldLabel = new javax.swing.JLabel();
        PwFieldLabel = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTextLabel.setFont(new java.awt.Font("나눔스퀘어", 0, 13)); // NOI18N
        loginTextLabel.setForeground(new java.awt.Color(102, 102, 102));
        loginTextLabel.setText("로그인");
        loginTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTextLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginTextLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginTextLabelMouseExited(evt);
            }
        });
        signUpPanel.add(loginTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 530, 40, 30));

        signUpBtn.setBackground(new java.awt.Color(255,255,255,0)
        );
        signUpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/signUp_btn.png"))); // NOI18N
        signUpBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        signUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpBtnMouseExited(evt);
            }
        });
        signUpPanel.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 440, 194, 41));

        checkPwField.setBackground(new java.awt.Color(255,255,255,0));
        checkPwField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        checkPwField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                checkPwFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                checkPwFieldFocusLost(evt);
            }
        });
        signUpPanel.add(checkPwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 240, 30));

        checkPwLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/field/normal/check_field.png"))); // NOI18N
        signUpPanel.add(checkPwLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 266, 22));

        signUpIdTextField.setBackground(new java.awt.Color(255,255,255,0));
        signUpIdTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        signUpIdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpIdTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpIdTextFieldFocusLost(evt);
            }
        });
        signUpPanel.add(signUpIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 240, 30));

        signUpIdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/id_field.png"))); // NOI18N
        signUpPanel.add(signUpIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 266, 20));

        signUpPwTextField.setBackground(new java.awt.Color(255,255,255,0));
        signUpPwTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        signUpPwTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signUpPwTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signUpPwTextFieldFocusLost(evt);
            }
        });
        signUpPanel.add(signUpPwTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 240, 30));

        signUpPwLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/pw_field.png"))); // NOI18N
        signUpPanel.add(signUpPwLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 266, 22));

        signUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/background/SignUp.png"))); // NOI18N
        signUpPanel.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorLabel.setBackground(new java.awt.Color(255,255,255,0));
        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        loginPanel.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 210, 20));

        LoginBtn.setBackground(new java.awt.Color(255,255,255,0));
        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/login_btn.png"))); // NOI18N
        LoginBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
        });
        loginPanel.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 420, 194, 41));

        SignUpTextLabel.setFont(new java.awt.Font("나눔스퀘어", 0, 13)); // NOI18N
        SignUpTextLabel.setForeground(new java.awt.Color(102, 102, 102));
        SignUpTextLabel.setText("회원가입");
        SignUpTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpTextLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpTextLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpTextLabelMouseExited(evt);
            }
        });
        loginPanel.add(SignUpTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 50, 30));

        idTextField.setBackground(new java.awt.Color(255,255,255,0));
        idTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFieldFocusLost(evt);
            }
        });
        loginPanel.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 240, 30));

        pwTextField.setBackground(new java.awt.Color(255,255,255,0));
        pwTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pwTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwTextFieldFocusLost(evt);
            }
        });
        loginPanel.add(pwTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 240, 30));

        IdFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/id_field.png"))); // NOI18N
        loginPanel.add(IdFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 266, 20));

        PwFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/pw_field.png"))); // NOI18N
        loginPanel.add(PwFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 266, 22));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/background/Login.png"))); // NOI18N
        loginPanel.add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(signUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(signUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* 로그인 이벤트 리스너(컨트롤러) 등록 메소드 */
    public void setLoginListner(ActionListener listener) {
        this.LoginBtn.addActionListener(listener);
    }
    
    /* 회원가입 이벤트 리스너(컨트롤러) 등록 메소드 */
    public void setSignUpListner(ActionListener listener){
        this.signUpBtn.addActionListener(listener);
    }

    /* 회원가입 버튼 마우스 이벤트 */
    private void SignUpTextLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTextLabelMouseEntered
        // TODO add your handling code here:
        SignUpTextLabel.setForeground(new Color(0, 142, 244, 255));
        SignUpTextLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SignUpTextLabelMouseEntered

    private void SignUpTextLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTextLabelMouseExited
        // TODO add your handling code here:
        SignUpTextLabel.setForeground(new Color(102, 102, 102, 255));
        SignUpTextLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_SignUpTextLabelMouseExited

    /* 로그인 버튼 마우스 이벤트 */
    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        // TODO add your handling code here:
        LoginBtn.setIcon(new ImageIcon("./src/resources/layout/button/hover/login_hover.png"));
        LoginBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        // TODO add your handling code here:
        LoginBtn.setIcon(new ImageIcon("./src/resources/layout/button/normal/login_btn.png"));
        LoginBtn.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_LoginBtnMouseExited

    /* 아이디 필드 포커스 이벤트 */
    private void idTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusGained
        // TODO add your handling code here:
        this.IdFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/hover/id_field_focus.png"));
        this.IdFieldLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_idTextFieldFocusGained

    private void idTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusLost
        // TODO add your handling code here:
        this.IdFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/normal/id_field.png"));
//        this.IdFieldLabel.setOpaque(false);
        this.IdFieldLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_idTextFieldFocusLost


    /* 비밀번호 필드 포커스 이벤트 */
    private void pwTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwTextFieldFocusGained
        // TODO add your handling code here:
        this.PwFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/hover/pw_field_focus.png"));
        this.PwFieldLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pwTextFieldFocusGained

    private void pwTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwTextFieldFocusLost
        // TODO add your handling code here:
        this.PwFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/normal/pw_field.png"));
        this.PwFieldLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pwTextFieldFocusLost
    
    /* 회원가입 비밀번호 필드 포커스 이벤트 */
    private void signUpPwTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPwTextFieldFocusGained
        // TODO add your handling code here:
        this.signUpPwLabel.setIcon(new ImageIcon("./src/resources/layout/button/hover/pw_field_focus.png"));
        this.signUpPwLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signUpPwTextFieldFocusGained

    private void signUpPwTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpPwTextFieldFocusLost
        // TODO add your handling code here:
        this.signUpPwLabel.setIcon(new ImageIcon("./src/resources/layout/button/normal/pw_field.png"));
        this.signUpPwLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_signUpPwTextFieldFocusLost
    
    /* 회원가입 아이디 필드 포커스 이벤트 */
    private void signUpIdTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpIdTextFieldFocusGained
        // TODO add your handling code here:
        this.signUpIdLabel.setIcon(new ImageIcon("./src/resources/layout/button/hover/id_field_focus.png"));
        this.signUpIdLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signUpIdTextFieldFocusGained

    private void signUpIdTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signUpIdTextFieldFocusLost
        // TODO add your handling code here:
        this.signUpIdLabel.setIcon(new ImageIcon("./src/resources/layout/button/normal/id_field.png"));
        this.signUpIdLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_signUpIdTextFieldFocusLost

    private void SignUpTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTextLabelMouseClicked
        // TODO add your handling code here:
        JPanelSetting.changePanel(panelList, signUpPanel);
    }//GEN-LAST:event_SignUpTextLabelMouseClicked

    /* 회원가입 버튼 마우스 이벤트 */
    private void signUpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseEntered
        // TODO add your handling code here:
        this.signUpBtn.setIcon(new ImageIcon("./src/resources/layout/button/hover/signUp_hover.png"));
        this.signUpBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_signUpBtnMouseEntered

    private void signUpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtnMouseExited
        // TODO add your handling code here:
        this.signUpBtn.setIcon(new ImageIcon("./src/resources/layout/button/normal/signUp_btn.png"));
        this.signUpBtn.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_signUpBtnMouseExited

    /* 로그인 이동 텍스트 마우스 이벤트 */
    private void loginTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTextLabelMouseClicked
        // TODO add your handling code here:
        JPanelSetting.changePanel(panelList, loginPanel);
    }//GEN-LAST:event_loginTextLabelMouseClicked

    private void loginTextLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTextLabelMouseEntered
        // TODO add your handling code here:
        loginTextLabel.setForeground(new Color(0, 142, 244, 255));
        loginTextLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_loginTextLabelMouseEntered

    private void loginTextLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTextLabelMouseExited
        // TODO add your handling code here:
        loginTextLabel.setForeground(new Color(102, 102, 102, 255));
        loginTextLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loginTextLabelMouseExited

    /* 비밀번호 체크 필드 포커스 이벤트 */
    private void checkPwFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkPwFieldFocusGained
        // TODO add your handling code here:
        this.checkPwLabel.setIcon(new ImageIcon("./src/resources/layout/field/focus/check_field_focus.png"));
        this.checkPwLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_checkPwFieldFocusGained

    private void checkPwFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkPwFieldFocusLost
        // TODO add your handling code here:
        this.checkPwLabel.setIcon(new ImageIcon("./src/resources/layout/field/normal/check_field.png"));
        this.checkPwLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_checkPwFieldFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginJFrame().setVisible(true);
        });
    }

    public JLabel getBackgroundLabel() { return BackgroundLabel; }

    public JPanel getBackgroundPanel() {
        return loginPanel;
    }

    public JLabel getIdFieldLabel() {
        return IdFieldLabel;
    }

    public JLabel getPwFieldLabel() {
        return PwFieldLabel;
    }

    public JLabel getSignUpTextLabel() {
        return SignUpTextLabel;
    }

    public JButton getLoginBtn() {
        return LoginBtn;
    }

    public JTextField getIdTextField() {
        return idTextField;
    }

    public JPasswordField getPwTextField() {
        return pwTextField;
    }

    public ArrayList<JPanel> getPanelList() {
        return panelList;
    }

    public JPasswordField getCheckPwField() {
        return checkPwField;
    }

    public JLabel getCheckPwLabel() {
        return checkPwLabel;
    }

    public JLabel getErrorLabel() {
        return errorLabel;
    }

    public JPanel getLoginPanel() {
        return loginPanel;
    }

    public JLabel getLoginTextLabel() {
        return loginTextLabel;
    }

    public JButton getSignUpBtn() {
        return signUpBtn;
    }

    public JLabel getSignUpIdLabel() {
        return signUpIdLabel;
    }

    public JTextField getSignUpIdTextField() {
        return signUpIdTextField;
    }

    public JLabel getSignUpLabel() {
        return signUpLabel;
    }

    public JPanel getSignUpPanel() {
        return signUpPanel;
    }

    public JLabel getSignUpPwLabel() {
        return signUpPwLabel;
    }

    public JPasswordField getSignUpPwTextField() {
        return signUpPwTextField;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JLabel IdFieldLabel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel PwFieldLabel;
    private javax.swing.JLabel SignUpTextLabel;
    private javax.swing.JPasswordField checkPwField;
    private javax.swing.JLabel checkPwLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTextLabel;
    private javax.swing.JPasswordField pwTextField;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel signUpIdLabel;
    private javax.swing.JTextField signUpIdTextField;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signUpPwLabel;
    private javax.swing.JPasswordField signUpPwTextField;
    // End of variables declaration//GEN-END:variables
}
