/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WePLi;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Donghyeon <20183188>
 */
public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        setResizable(false); // 크기 변경 불가능하도록 함
        setUndecorated(true); // 프레임의 타이틀바를 없앰
        
        initComponents();

        setVisible(true);
        // 화면 중앙에서 실행
        setLocationRelativeTo(null);
        
        
          this.LoginBtn.setOpaque(false);
          
          this.idTextField.setBackground(new Color(255,255,255,0));
          this.idTextField.setOpaque(false);
          
          this.pwTextField.setBackground(new Color(255,255,255,0));
          this.pwTextField.setOpaque(false);
          
//        IdTextField.setForeground(new Color(187,187,187, 255));
//        PwTextField.setForeground(new Color(187,187,187, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        SignUpTextLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        pwTextField = new javax.swing.JPasswordField();
        IdFieldLabel = new javax.swing.JLabel();
        PwFieldLabel = new javax.swing.JLabel();
        BackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBtn.setBackground(new java.awt.Color(255,255,255,0));
        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/login_btn.png"))); // NOI18N
        LoginBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
        });
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        BackgroundPanel.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 194, 41));

        SignUpTextLabel.setFont(new java.awt.Font("나눔스퀘어", 0, 13)); // NOI18N
        SignUpTextLabel.setForeground(new java.awt.Color(102, 102, 102));
        SignUpTextLabel.setText("회원가입");
        SignUpTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpTextLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpTextLabelMouseExited(evt);
            }
        });
        BackgroundPanel.add(SignUpTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 50, 30));

        idTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFieldFocusLost(evt);
            }
        });
        BackgroundPanel.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 240, 30));

        pwTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pwTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwTextFieldFocusLost(evt);
            }
        });
        BackgroundPanel.add(pwTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 240, 30));

        IdFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/id_field.png"))); // NOI18N
        BackgroundPanel.add(IdFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 266, 20));

        PwFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/button/normal/pw_field.png"))); // NOI18N
        BackgroundPanel.add(PwFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 266, 22));

        BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/layout/background/Login.png"))); // NOI18N
        BackgroundPanel.add(BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Controller 이벤트 리스너(컨트롤러) 등록 메소드 */
    public void setLoginListner(ActionListener listener){
        this.LoginBtn.addActionListener(listener);
    }
        
    /* 회원가입 버튼 마우스 이벤트 */
    private void SignUpTextLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTextLabelMouseEntered
        // TODO add your handling code here:
        SignUpTextLabel.setForeground(new Color(0, 142, 244, 255));
        SignUpTextLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SignUpTextLabelMouseEntered

    private void SignUpTextLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTextLabelMouseExited
        // TODO add your handling code here:
        SignUpTextLabel.setForeground(new Color(102, 102, 102, 255));
        SignUpTextLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_SignUpTextLabelMouseExited
    
    /* 로그인 버튼 마우스 이벤트 */
    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        // TODO add your handling code here:
        LoginBtn.setIcon(new ImageIcon("./src/resources/layout/button/hover/login_hover.png"));
        LoginBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LoginBtnMouseEntered

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        // TODO add your handling code here:
        LoginBtn.setIcon(new ImageIcon("./src/resources/layout/button/normal/login_btn.png"));
        LoginBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LoginBtnMouseExited

    
    /* 아이디 필드 포커스 이벤트 */
    private void idTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusGained
        // TODO add your handling code here:
        this.IdFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/hover/id_field_focus.png"));
        this.IdFieldLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_idTextFieldFocusGained

    private void idTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusLost
        // TODO add your handling code here:
        this.IdFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/normal/id_field.png"));
//        this.IdFieldLabel.setOpaque(false);
        this.IdFieldLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_idTextFieldFocusLost


    /* 비밀번호 필드 포커스 이벤트 */
    private void pwTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwTextFieldFocusGained
        // TODO add your handling code here:
        this.PwFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/hover/pw_field_focus.png"));
        this.PwFieldLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pwTextFieldFocusGained

    private void pwTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwTextFieldFocusLost
        // TODO add your handling code here:
        this.PwFieldLabel.setIcon(new ImageIcon("./src/resources/layout/button/normal/pw_field.png"));
        this.PwFieldLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pwTextFieldFocusLost

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }
    
    public JLabel getBackgroundLabel() { return BackgroundLabel; }
    public JPanel getBackgroundPanel() { return BackgroundPanel; }
    public JLabel getIdFieldLabel() { return IdFieldLabel; }
    public JLabel getPwFieldLabel() {  return PwFieldLabel; }
    public JLabel getSignUpTextLabel() { return SignUpTextLabel; }
    public JButton getLoginBtn() { return LoginBtn; }
    public JTextField getIdTextField() { return idTextField; }
    public JPasswordField getPwTextField() { return pwTextField; }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLabel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel IdFieldLabel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel PwFieldLabel;
    private javax.swing.JLabel SignUpTextLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPasswordField pwTextField;
    // End of variables declaration//GEN-END:variables
}
